sudo: false
language: node_js
node_js: 8.3.0
cache: npm
git: { depth: 3 }

service:
  - mysql
  - postgres

install:
  - yarn install
  - mysql -e 'CREATE DATABASE testdb; CREATE TABLE testdb.table1 (`id` int(11) NOT NULL AUTO_INCREMENT, `name` varchar(20) NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=UTF8'
  - mysql -e 'INSERT INTO testdb.table1 (name) VALUES ("User 1"),("User 2"),("User 3");'
  - psql -c 'CREATE TABLE table1 (name varchar(20) not null);'  -U postgres
  - psql -c "INSERT INTO table1 (name) VALUES ('User 1');"  -U postgres
  - psql -c "INSERT INTO table1 (name) VALUES ('User 2')"  -U postgres
  - psql -c "INSERT INTO table1 (name) VALUES ('User 3');"  -U postgres

script:
  - npm test
  - npm run itest
  - npm run coverage
