app:
  name: Test Application
  context:
    name: BaseContext
  server:
    port: 10010

logging:
  streams:
    console:
      type: console
    myredis:
      type: redis
    mainLogFile:
      type: file
      path: main.log
  loggers:
    - name: ROOT
      streams:
        console: debug
#        myredis: info
#        mainLogFile: debug
    - name: ioc/
      streams:
        console: debug
#        myredis: info
    - name: mysql/
      streams:
        console: debug
#        myredis: info

metrics:
  gateway:
    active: 0

MySQL:
  MysqlClient: # this is the name of the object that will be exposed in the context
    master:
      host: localhost
      port: 3306
      user: root
      password:
      database: testDb
      charset: utf8
      connectionLimit: 10
    slave:
      host: localhost
      port: 3306
      user: root
      password:
      database: testDb
      charset: utf8
      connectionLimit: 10

Context:
  ActiveProfiles: development

Application:
  Parameter1: Value 1
