app:
  name: Test Application
  context:
    name: BaseContext
  server:
    port: 10010
  xmlRoot: ''

logging:
  streams:
    console:
      type: console
    myredis:
      type: redis
    mainLogFile:
      type: file
      path: main.log
  loggers:
    - name: ROOT
      streams:
        console: debug
#        myredis: info
#        mainLogFile: debug
    - name: ioc/
      streams:
        console: debug
#        myredis: info
    - name: mysql/
      streams:
        console: debug
#        myredis: info

metrics:
  gateway:
    active: 0

mysql:
  MysqlClient: # this is the name of the object that will be exposed in the context
    master:
      max: 10
      min: 1
      maxWaitingClients: 10
      testOnBorrow: false
      acquireTimeoutMillis: 2000
      evictionRunIntervalMillis: 30000
      numTestsPerRun: 3
      idleTimeoutMillis: 30000
      connectionConfig:
        host: localhost
        port: 3306
        user: root
        password: 
        database: testDb
        charset: utf8
    slave:
      max: 10
      min: 1
      maxWaitingClients: 10
      testOnBorrow: false
      acquireTimeoutMillis: 2000
      evictionRunIntervalMillis: 30000
      numTestsPerRun: 3
      idleTimeoutMillis: 30000
      connectionConfig:
        host: localhost
        port: 3306
        user: root
        password: 
        database: testDb
        charset: utf8

postgres:
  PostgresClient:
    master:
      max: 10
      min: 1
      maxWaitingClients: 10
      testOnBorrow: false
      acquireTimeoutMillis: 2000
      evictionRunIntervalMillis: 30000
      numTestsPerRun: 3
      idleTimeoutMillis: 30000
      connectionConfig:
        host: localhost
        port: 5432
        user: postgres
        password: 
        database: postgres
        application_name: test
    slave:
      max: 10
      min: 1
      maxWaitingClients: 10
      testOnBorrow: false
      acquireTimeoutMillis: 2000
      evictionRunIntervalMillis: 30000
      numTestsPerRun: 3
      idleTimeoutMillis: 30000
      connectionConfig:
        host: localhost
        port: 5432
        user: postgres
        password: 
        database: postgres
        application_name: test

SqsWorker:
  myTestSqsWorker:
    handlerObject: MyHandler
    queueUrl: http://localhost:9324

SqsClient:
  myTestSqsClient:
    queueUrl: http://localhost:9324

elasticsearch:
  elastic:
    hosts:
      - host: localhost
        port: 9200
        protocol: http

rabbitmq:
  client:
    hostname: localhost
    port: 5672
    username: hip
    password: 
  producer:
    peter:
      exchangName: firehose
      backPressureStrategy: 0
  consumer:
    peter:
      appQueueName: nuntius.mandrill.queue
      delayQueueName: nuntius.mandrill.delay.queue
      dlqName: nuntius.mandrill.dlq
      messageHandler: MessageHandler
      maxRetries: 4
      retryDelayInMinute: 2
      retryDelayFactor: 1

Context:
  ActiveProfiles: development

Application:
  Parameter1: Value 1
