app:
  name: Test Application
  context:
    name: BaseContext
  server:
    port: 10010
  xmlRoot: ''

logging:
  streams:
    console:
      type: console
    myredis:
      type: redis
    mainLogFile:
      type: file
      path: main.log
  loggers:
    - name: ROOT
      streams:
        console: debug
#        myredis: info
#        mainLogFile: debug
    - name: ioc/
      streams:
        console: debug
#        myredis: info
    - name: mysql/
      streams:
        console: debug
#        myredis: info

metrics:
  gateway:
    active: 0
