apiVersion: v1
kind: Service
metadata:
  name: localstack-inceptum
spec:
  type: NodePort
  ports:
  - port: 8080
    name: webui
  - port: 4575
    name: sns
  - port: 4576
    name: sqs
  - port: 4565
    name: sqs-rest
  selector:
    app: localstack-inceptum
---
apiVersion: apps/v1beta1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: localstack-inceptum
spec:
  selector:
    matchLabels:
      app: localstack-inceptum
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: localstack-inceptum
    spec:
      containers:
      - image: localstack/localstack:0.8.6
        name: localstack
        env:
          # Use secret in real usage
        - name: SERVICES
          value: "sqs,sns"
        - name: DEFAULT_REGION
          value: "ap-southeast-2"
        - name: USE_SSL
          value: "false"
        ports:
        - containerPort: 8080
          name: webui
        - containerPort: 4575
          name: sns
        - containerPort: 4576
          name: sqs
        - containerPort: 4565
          name: sqs-rest
