apiVersion: v1
kind: Service
metadata:
  name: postgres-inceptum
spec:
  type: NodePort
  ports:
  - port: 5432
  selector:
    app: postgres-inceptum
---
apiVersion: apps/v1beta1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: postgres-inceptum
spec:
  selector:
    matchLabels:
      app: postgres-inceptum
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres-inceptum
    spec:
      containers:
      - image: postgres:9-alpine
        name: postgres
        env:
        - name: POSTGRES_PASSWORD
          value: inceptum
        ports:
        - containerPort: 5432
          name: postgres